//  ___VARIABLE_classPrefix:identifier___ViewController.h
//
//  Generated by the the BeachFrontBuilder Xcode Project Template on ___DATE___.
//

#import <UIKit/UIKit.h>
#import <BeachFrontBuilderSDK/BeachFrontBuilderSDK.h>

@interface ___VARIABLE_classPrefix:identifier___HomeViewController : UITableViewController <UISplitViewControllerDelegate>

@property (strong, nonatomic) BFChannelViewController *detailViewController;
@property (strong, nonatomic) UIPopoverController* masterPopoverController;

@end